version: '3'
services: 
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 267552
      MYSQL_DATABASE: address
      MYSQL_USER: daming
      MYSQL_PASSWORD: 267552
    ports:
      - "3306:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"