version: '3'
services: 
  # address:
  #   build: ./
  #   image: address-api:latest
  #   container_name: address-api
  #   command: main
  #   restart: always
  #   env_file: .env
  #   ports:
  #       - "9999:9999"
  #   depends_on: 
  #     - mysql
  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - address-go:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 267552
      MYSQL_DATABASE: address
      MYSQL_USER: daming
      MYSQL_PASSWORD: 267552
    ports:
      - "3306:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks: 
      - address-networks
volumes:
  address-go:
    external: true
    
networks:
  address-networks:
    external: true
