apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: address-go-mysql-pv-claim
  namespace: address-go-namespace
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: address-go-mysql-pv-volume
  namespace: address-go-namespace
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: address-go-namespace
  labels:
    app: mysql
data:
  MYSQL_ROOT_PASSWORD: "267552"
  MYSQL_DATABASE: address
  MYSQL_USER: daming
  MYSQL_PASSWORD: "267552"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: address-go-namespace
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          envFrom:
            - configMapRef:
                name: mysql-config
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-data
              mountPath: var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: address-go-mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: address-go-namespace
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  type: NodePort
  selector:
    app: mysql
