name: Daming Address CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [ 1.18 ]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Download vender
        run: go mod download
      - name: Build
        run: make run
      - name: Build with bazel
        run: make bazel