name: Daming Address CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: ["1.21.6"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download vender
        run: go mod download
      - name: Build
        run: make build
      - name: Build with bazel
        run: make bazel
  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: ["1.21.6"]
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Bazel cache
        id: bazel-cache
        uses: actions/cache@v2
        env:
          version: 5.0.0
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-{{ env.version }}-bazel-cache
      # https://github.com/bytecodealliance/wasmtime-go/blob/main/.github/workflows/main.yml
      - name: Ready msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-toolchain
          path-type: inherit
      - name: Build with bazel
        shell: msys2 {0}
        run: bazel build //cmd/address:address --compiler=mingw-gcc --verbose_failures && bazel build //cmd/migrate:migrate --compiler=mingw-gcc --verbose_failures
